### ISSUE TITLE
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by flik** [cloverinteractive/cms#25] opened 2015-03-15 11:28 UTC
When I start bundle install. It is returning this error

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb 
```

Gem files will remain installed in /var/lib/gems/1.9.1/gems/capybara-webkit-0.12.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/capybara-webkit-0.12.1/./gem_make.out
An error occurred while installing capybara-webkit (0.12.1), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '0.12.1'` succeeds before bundling.

**Comment by aalvarado** [comment] 2015-03-16 05:54
You might want to check out why `capybara-webkit` fails to build in your computer, you might be missing some libs. if you could post the contents of the logged results we could probably tell you why it failed. It would also be helpful if you take a look at issues in the capybara-webkit project and see if there's an answer for your issue. 

You can check out their wiki here: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit

I'm closing this as the issue is with a 3rd party gem, not with the application itself.

**Closed as completed by aalvarado** 2015-03-16 05:54 UTC

**Comment by flik** [comment] 2015-03-16 09:47
Actually, Your application is dependent on the 3rd party gem which is not working. Even I have installed it separately but still getting error.

**Comment by aalvarado** [comment] 2015-03-16 23:16
not sure what you mean by that. If it's third party and you can't build it by itself, I think it would make sense to try and resolve that issue first with the help of the gem's creators. don't you agree?

**Comment by flik** [comment] 2015-03-17 09:40
Well. I will try again.
